### ISSUE TITLE
Tone lag in iOS 11

### ISSUE THREAD

**Issue by lincbarr** [ooper-shlab/ToneGenerator1.0-Swift#1]
ToneGenerator1.0 works perfectly through iOS10. In iOS 11: Play the 440 hz tone then stop. Change the frequency, press start. The 440 Hz signal plays for a moment then the new tone is played. Change the frequency again and the old frequency plays for a moment before the new frequency.

**Comment by ooper-shlab** [comment]
Thanks for reporting. I'll check it when I can make some time for it.

**Comment by tiemenc** [comment]
Hi, in the first place I wanted to thank you for the very useful AVTonePlayerUnit subclass! I also had some issues (app hanging randomly) after upgrading to iOS11. (to reproduce this: start the sound and click start/stop about 50 times). It appears this problem sometimes occurs with the tone.stop() (hence AVTonePlayerUnit stop) function in AVFoundation. In iOS11 it seems to lead to concurrency issues, debugging pointed to __psynch_mutexwait. Using tone.pause() instead solved the issue for now.
Also (probably unrelated), the tone lag disappears after turning off and on the engine with engine.stop() / engine.start(). It's a workaround but may be of use if you plan to start/stop the sound regularly.

**Comment by lincbarr** [comment]
Thank you for getting back to me. I encountered the same issues as you did. I wound up recording the tones I needed and playing them in loops. I would prefer to use the Tone Generator, but it looks like we have to wait for a fix from Apple.

Best wishes,

— Lincoln Barr —


Mr. J. Lincoln Barr

j.lincoln.barr@gmail.com

**Comment by ooper-shlab** [comment]
Sorry to have kept this issue for so long. I have merged ziyaointl's pull request, and the original issue #1 seems to be fixed. I have not tried to reproduce the issue described by tiemenc, but if it still happens and is a big issue, someone please report it as another issue. Thanks to all who has contributed to fix this issue.
